const GET_CHATS = 'GET_CHATS';
const GET_CHATS_SUCCESS = 'GET_CHATS_SUCCESS';
const CHATS_ERROR = 'CHATS_ERROR';
const UPDATE_CHATS = 'UPDATE_CHATS';
const GET_CHAT_INFORMATION = 'GET_CHAT_INFORMATION';
const GET_CHAT_INFORMATION_SUCCESS = 'GET_CHAT_INFORMATION_SUCCESS';
const UPDATE_CHAT_INFORMATION = 'UPDATE_CHAT_INFORMATION';
const SELECT_CHAT = 'SELECT_CHAT';
const SET_SELECTED_MESSAGES = 'SET_SELECTED_MESSAGES';
const UPDATE_CHAT_MESSAGE = 'UPDATE_CHAT_MESSAGE';
const DELETE_CHANNEL = 'DELETE_CHANNEL';
const DELETE_CHANNEL_SUCCESS = 'DELETE_CHANNEL_SUCCESS';
const DELETE_CONTACT = 'DELETE_CONTACT';

export default {
  GET_CHATS,
  GET_CHATS_SUCCESS,
  GET_CHAT_INFORMATION,
  GET_CHAT_INFORMATION_SUCCESS,
  UPDATE_CHAT_INFORMATION,
  CHATS_ERROR,
  UPDATE_CHATS,
  SELECT_CHAT,
  SET_SELECTED_MESSAGES,
  UPDATE_CHAT_MESSAGE,
  DELETE_CHANNEL,
  DELETE_CHANNEL_SUCCESS,
  DELETE_CONTACT
}
