const GET_CHATS = 'GET_CHATS';
const GET_CHATS_SUCCESS = 'GET_CHATS_SUCCESS';
const CHATS_ERROR = 'CHATS_ERROR';
const GET_CHAT_INFORMATION = 'GET_CHAT_INFORMATION';
const GET_CHAT_INFORMATION_SUCCESS = 'GET_CHAT_INFORMATION_SUCCESS';
const SELECT_CHAT = 'SELECT_CHAT';
const SET_SELECTED_MESSAGES = 'SET_SELECTED_MESSAGES';
const UPDATE_CHAT_MESSAGE = 'UPDATE_CHAT_MESSAGE';

export default {
  GET_CHATS,
  GET_CHATS_SUCCESS,
  GET_CHAT_INFORMATION,
  GET_CHAT_INFORMATION_SUCCESS,
  CHATS_ERROR,
  SELECT_CHAT,
  SET_SELECTED_MESSAGES,
  UPDATE_CHAT_MESSAGE
}
