const GET_CHATS = 'GET_CHATS';
const GET_CHATS_SUCCESS = 'GET_CHATS_SUCCESS';
const CHATS_ERROR = 'CHATS_ERROR';
const SELECT_CHAT = 'SELECT_CHAT';
const SET_SELECTED_MESSAGES = 'SET_SELECTED_MESSAGES';

export default {
  GET_CHATS,
  GET_CHATS_SUCCESS,
  CHATS_ERROR,
  SELECT_CHAT,
  SET_SELECTED_MESSAGES
}
